name: ci

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - uses: neondatabase/create-branch-action@v4
        with:
          project_id: throbbing-boat-70555201
          branch_name: github_actions
          api_key: ${{ secrets.NEON_API_KEY }}
        id: create-branch
      - run: pnpm generate
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url }}
      - uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ steps.create-branch.outputs.project_id }}
          branch: ${{ steps.create-branch.outputs.branch_id }}
          api_key: ${{ secrets.NEON_API_KEY }}
      - run: pnpm check:lint
      - run: pnpm check:format
      - run: pnpm check:styles
      - run: pnpm check:types
